print "the backspace escape character the hihello will  be  ==  hi\bhello"
print "print backslash  \\"
print "print single quotes \'"
print "print double quotes \""
print "Ascii formattes escape character  Hello\fworld"
print "horizontal tab hihello will be == hi\thello"
print "print in new line \n"
print "hi hello"
print "Bell sound \a"
print "Vertical tab  hi\vhello"
print "using \\x escape character to print corresponding char from hexadecimal value  --  \x61"