import math
a=input('Enter a\n')
b=input('Enter b\n')

print "sin of a is",math.sin(a)
print "sin of b is",math.sin(b)
print "cos of a is",math.cos(a)
print "cos of b is",math.cos(b)
print "tan of a is",math.tan(a)
print "tan of b is",math.tan(b)
print "asin of a is",math.asin(a)
print "asin of b is",math.asin(b)
print "acos of a is",math.acos(a)
print "acos of b is",math.acos(b)
print "atan of a is",math.atan(a)
print "atan of b is",math.atan(b)
print "sinh of a is",math.sinh(a)
print "sinh of b is",math.sinh(b)
print "cosh of a is",math.cosh(a)
print "cosh of b is",math.cosh(b)
print "tanh of a is",math.tanh(a)
print "tanh of b is",math.tanh(b)
print "asinh of a is",math.asinh(a)
print "asinh of b is",math.asinh(b)
print "acosh of a is",math.acosh(a)
print "acosh of b is",math.acosh(b)
print "atanh of a is",math.atanh(a)
print "atanh of b is",math.atanh(b)
